#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
from geometry_msgs.msg import Twist
from sensor_msgs.msg import Imu

class ImuSoftController(object):
    def __init__(self):
        rospy.init_node("imu_soft_controller")

        self.cmd_in_topic  = rospy.get_param("~cmd_in_topic",  "/cmd_vel_raw")
        self.cmd_out_topic = rospy.get_param("~cmd_out_topic", "/cmd_vel")
        self.imu_topic     = rospy.get_param("~imu_topic",     "/imu/data")

        self.rate_hz   = rospy.get_param("~rate", 30.0)
        self.max_accel = rospy.get_param("~max_accel", 0.4)
        self.max_decel = rospy.get_param("~max_decel", 0.6)

        self.cmd_timeout = rospy.get_param("~cmd_timeout", 0.5)

        self.gyro_y_thresh = rospy.get_param("~gyro_y_thresh", 1.5)
        self.bump_speed    = rospy.get_param("~bump_speed", 0.08)
        self.bump_hold     = rospy.get_param("~bump_hold", 2.0)
        self.bump_min_interval = rospy.get_param("~bump_min_interval", 1.0)

        self.last_raw_cmd = Twist()
        self.last_cmd_time = rospy.Time.now().to_sec()

        self.current_v = 0.0
        self.last_out_time = rospy.Time.now().to_sec()

        self.gyro_y = 0.0
        self.bump_active = False
        self.last_bump_time = 0.0

        self.pub_cmd = rospy.Publisher(self.cmd_out_topic, Twist, queue_size=1)
        rospy.Subscriber(self.cmd_in_topic, Twist, self.cb_cmd)
        rospy.Subscriber(self.imu_topic, Imu, self.cb_imu)

        rospy.loginfo("[IMU_SOFT] READY")
        self.loop()

    def cb_cmd(self, msg):
        self.last_raw_cmd = msg
        self.last_cmd_time = rospy.Time.now().to_sec()

    def cb_imu(self, msg):
        self.gyro_y = msg.angular_velocity.y
        now = rospy.Time.now().to_sec()

        if abs(self.gyro_y) > self.gyro_y_thresh:
            if (now - self.last_bump_time) > self.bump_min_interval:
                rospy.loginfo("[IMU] Bump detected! gyro_y=%.3f" % self.gyro_y)
                self.last_bump_time = now
                self.bump_active = True

        if self.bump_active and (now - self.last_bump_time) > self.bump_hold:
            rospy.loginfo("[IMU] Bump finished")
            self.bump_active = False

    def loop(self):
        rate = rospy.Rate(self.rate_hz)

        while not rospy.is_shutdown():
            now = rospy.Time.now().to_sec()

            age_cmd = now - self.last_cmd_time
            if age_cmd > self.cmd_timeout:
                v_target = 0.0
                raw_cmd = Twist()
            else:
                raw_cmd = self.last_raw_cmd
                v_target = raw_cmd.linear.x

            if self.bump_active and v_target > self.bump_speed:
                v_target = self.bump_speed

            dt = now - self.last_out_time
            if dt <= 0.0:
                dt = 1.0 / self.rate_hz

            dv = v_target - self.current_v
            max_up = self.max_accel * dt
            max_dn = self.max_decel * dt

            if dv > max_up:
                dv = max_up
            elif dv < -max_dn:
                dv = -max_dn

            self.current_v += dv

            out = Twist()
            out.linear.x  = self.current_v
            out.angular.z = raw_cmd.angular.z

            self.pub_cmd.publish(out)
            self.last_out_time = now

            rate.sleep()


if __name__ == "__main__":
    try:
        ImuSoftController()
    except rospy.ROSInterruptException:
        pass
